// Generated by CoffeeScript 1.9.2
(function() {
  define(["jquery", "jquery.elmenu"], function($) {
    return $('.js-elmenu').elmenu({
      items: [
        {
          name: 'El Taco',
          link: 'http://goo.gl/LcBkbd'
        }, {
          name: 'El Burrito',
          link: 'http://goo.gl/bYMnrY'
        }, {
          name: 'El Sambrero',
          link: 'http://goo.gl/SpuFzx'
        }
      ]
    });
  });

}).call(this);

//# sourceMappingURL=lesson3.js.map
